import type { Language } from '../types.js';

/**
 * Заготовки ответов заглушки.
 *
 * Шаблон выбирается по ключевым словам в запросе, а если ничего не совпало —
 * случайный из общих. Тексты размечены markdown: интерфейс проверяет на них
 * списки, таблицы и блоки кода.
 */
interface AnswerTemplate {
  id: string;
  triggers: readonly string[];
  ru: readonly string[];
  en: readonly string[];
}

const KEYWORD_TEMPLATES: readonly AnswerTemplate[] = [
  {
    id: 'greeting',
    triggers: ['привет', 'здравствуй', 'добрый день', 'добрый вечер', 'hello', 'hi ', 'hey'],
    ru: [
      'Привет! Я встроенная модель **Qwen 2.5 Coder** в Ketner AI — интеллектуальный ассистент',
      'для написания и анализа кода, проектирования архитектуры и решения инженерных задач.',
      '',
      'Что уже работает в интерфейсе:',
      '',
      '- **стриминг ответа** — текст приходит порциями в реальном времени;',
      '- **markdown** — списки, таблицы, `код` в строке и блоки кода с кнопкой «Копировать»;',
      '- **история** — диалоги сохраняются и переживают перезагрузку страницы;',
      '- **управление** — остановка генерации, повторная отправка и редактирование сообщения.',
      '',
      'Спросите меня о чём угодно: напишите функцию, сделайте рефакторинг или разберите архитектурный вопрос.',
    ],
    en: [
      'Hello! I am the built-in **Qwen 2.5 Coder** model in Ketner AI — an intelligent assistant',
      'designed for software engineering, code synthesis, architecture design, and problem solving.',
      '',
      'What already works in the interface:',
      '',
      '- **streaming output** — responses arrive progressively in real time;',
      '- **markdown** — lists, tables, inline `code`, and syntax-highlighted code blocks with Copy buttons;',
      '- **conversation history** — chats survive browser reloads and sync across devices;',
      '- **controls** — stop generation, regenerate, and edit previous messages.',
      '',
      'Ask me anything: refactor a function, architect a system, or analyze code.',
    ],
  },
  {
    id: 'qwen',
    triggers: ['qwen', 'квен', 'модель', 'кто ты', 'что за модель', 'who are you'],
    ru: [
      'Я — **Qwen 2.5 Coder**, флагманская открытая языковая модель нового поколения, встроенная в Ketner AI.',
      '',
      '### Специализация:',
      '- ⚡ **Продвинутое программирование**: TypeScript, JavaScript, Python, Go, Rust, C++, SQL.',
      '- 🛠️ **Инженерия и архитектура**: проектирование масштабируемых систем, рефакторинг, отладка багов.',
      '- 📊 **Работа со сложными данными**: генерация JSON, Markdown-таблиц, регулярных выражений.',
      '- 🌐 **Полная мультиязычность**: свободные ответы на русском и английском языках.',
      '',
      'Задайте мне любую задачу по коду или алгоритмам!',
    ],
    en: [
      'I am **Qwen 2.5 Coder**, the next-generation open weights coding foundation model built into Ketner AI.',
      '',
      '### Core competencies:',
      '- ⚡ **Advanced programming**: TypeScript, JavaScript, Python, Go, Rust, C++, SQL, and more.',
      '- 🛠️ **Engineering & Architecture**: clean code architecture, refactoring, vulnerability audit.',
      '- 📊 **Data handling**: schema synthesis, JSON formatting, Markdown tables, regex creation.',
      '- 🌐 **Full multilingual fluency**: natural communication in both Russian and English.',
      '',
      'Feel free to give me any coding or algorithmic challenge!',
    ],
  },
  {
    id: 'code',
    triggers: ['код', 'рефактор', 'функци', 'баг', 'code', 'refactor', 'function', 'bug'],
    ru: [
      '## Что можно улучшить',
      '',
      'Разложу замечания по приоритетам — от дешёвых правок к архитектурным.',
      '',
      '**1. Убрать повторяющиеся проверки**',
      '',
      '```ts',
      'type Nullable<T> = T | null | undefined;',
      '',
      'function present<T>(value: Nullable<T>): value is T {',
      '  return value !== null && value !== undefined;',
      '}',
      '',
      'const activeUsers = users.filter(present).filter((user) => user.active);',
      '```',
      '',
      '**2. Разделить чистые функции и побочные эффекты**',
      '',
      '- чистые функции — в `lib/`, их легко покрыть тестами;',
      '- работу с сетью и хранилищем — в `api/` и `store/`.',
      '',
      '**3. Проверить границы**',
      '',
      '| Случай | Что проверяем |',
      '| --- | --- |',
      '| Пустой ввод | функция не бросает исключение |',
      '| Очень длинный текст | обрезка не рвёт эмодзи |',
      '| Недоступный API | пользователь видит понятную ошибку |',
      '',
      'Пришлите сам код — разберу конкретные места построчно.',
    ],
    en: [
      '## What can be improved',
      '',
      'Here are the notes ordered by priority — from cheap fixes to architectural ones.',
      '',
      '**1. Remove repeated checks**',
      '',
      '```ts',
      'type Nullable<T> = T | null | undefined;',
      '',
      'function present<T>(value: Nullable<T>): value is T {',
      '  return value !== null && value !== undefined;',
      '}',
      '',
      'const activeUsers = users.filter(present).filter((user) => user.active);',
      '```',
      '',
      '**2. Separate pure functions from side effects**',
      '',
      '- pure functions belong in `lib/`, they are easy to test;',
      '- network and storage work belongs in `api/` and `store/`.',
      '',
      '**3. Cover the edges**',
      '',
      '| Case | What we check |',
      '| --- | --- |',
      '| Empty input | the function does not throw |',
      '| Very long text | truncation does not break emoji |',
      '| API unavailable | the user sees a clear error |',
      '',
      'Send the code itself and I will review the exact lines.',
    ],
  },
  {
    id: 'data',
    triggers: ['sql', 'nosql', 'бд', 'база данных', 'индекс', 'database', 'postgres', 'транзакц'],
    ru: [
      '### Коротко',
      '',
      'SQL — про жёсткую схему и связи, NoSQL — про свободную структуру и горизонтальное',
      'масштабирование. Выбирают не «что современнее», а что требует задача.',
      '',
      '| Критерий | SQL | NoSQL |',
      '| --- | --- | --- |',
      '| Схема | задаётся заранее, есть миграции | гибкая, поля могут отличаться |',
      '| Связи | `JOIN`, внешние ключи | вложенные документы или ручная сборка |',
      '| Масштабирование | вертикальное, реже шардирование | горизонтальное «из коробки» |',
      '| Гарантии | ACID по умолчанию | часто eventual consistency |',
      '',
      '**Когда SQL:** транзакции, отчётность, сложные связи, деньги и заказы.',
      '',
      '**Когда NoSQL:** быстро меняющаяся структура, огромный поток записей, кэш и сессии.',
      '',
      '> В прототипе Ketner AI диалоги и сообщения описаны как обычные таблицы: связи простые,',
      '> а согласованность данных важнее скорости записи.',
    ],
    en: [
      '### In short',
      '',
      'SQL is about a strict schema and relations, NoSQL is about a flexible structure and',
      'horizontal scaling. The choice follows the task, not the trend.',
      '',
      '| Criterion | SQL | NoSQL |',
      '| --- | --- | --- |',
      '| Schema | defined upfront, migrations | flexible, fields may differ |',
      '| Relations | `JOIN`, foreign keys | embedded documents or manual assembly |',
      '| Scaling | vertical, sharding later | horizontal out of the box |',
      '| Guarantees | ACID by default | often eventual consistency |',
      '',
      '**Choose SQL for:** transactions, reporting, complex relations, money and orders.',
      '',
      '**Choose NoSQL for:** fast changing structure, huge write volume, caches and sessions.',
      '',
      '> In the Ketner AI prototype conversations and messages are plain tables: relations are',
      '> simple, and consistency matters more than write speed.',
    ],
  },
  {
    id: 'plan',
    triggers: ['план', 'запуск', 'roadmap', 'недел', 'этап', 'plan', 'launch', 'week'],
    ru: [
      '## План запуска на 4 недели',
      '',
      '**Неделя 1 — фундамент**',
      '',
      '1. Зафиксировать метрику успеха и целевую аудиторию.',
      '2. Собрать лендинг и форму списка ожидания.',
      '',
      '**Неделя 2 — продукт**',
      '',
      '1. Довести основной сценарий до конца, без обходных путей.',
      '2. Закрыть дыры в онбординге и пустых состояниях.',
      '',
      '**Неделя 3 — приватная бета**',
      '',
      '1. Пригласить 20–30 человек из целевой аудитории.',
      '2. Собрать обратную связь по трём вопросам: что понятно, что мешает, за чем вернутся.',
      '',
      '**Неделя 4 — публичный запуск**',
      '',
      '1. Подготовить каналы: рассылка, профильные сообщества, личные приглашения.',
      '2. Держать наготове быстрые правки по итогам первой недели.',
      '',
      '| Риск | Как снижаем |',
      '| --- | --- |',
      '| Не хватает времени | оставляем один сценарий вместо трёх |',
      '| Мало отклика в бете | пишем участникам лично |',
    ],
    en: [
      '## Four week launch plan',
      '',
      '**Week 1 — foundation**',
      '',
      '1. Fix the success metric and the target audience.',
      '2. Ship the landing page and the waitlist form.',
      '',
      '**Week 2 — product**',
      '',
      '1. Bring the main flow to the end, without workarounds.',
      '2. Close the gaps in onboarding and empty states.',
      '',
      '**Week 3 — private beta**',
      '',
      '1. Invite 20–30 people from the target audience.',
      '2. Collect feedback on three questions: what is clear, what blocks them, what brings',
      '   them back.',
      '',
      '**Week 4 — public launch**',
      '',
      '1. Prepare the channels: newsletter, communities, personal invites.',
      '2. Keep quick fixes ready based on the first week.',
      '',
      '| Risk | How we reduce it |',
      '| --- | --- |',
      '| Not enough time | keep one flow instead of three |',
      '| Low beta response | message participants personally |',
    ],
  },
  {
    id: 'compare',
    triggers: ['сравн', 'разниц', 'таблиц', 'compare', 'difference', 'table', 'плюсы'],
    ru: [
      'Собрал сравнение в таблицу — так развилки видны сразу.',
      '',
      '| Подход | Плюсы | Минусы | Кому подходит |',
      '| --- | --- | --- | --- |',
      '| Готовое решение | быстрый старт | платно и мало гибкости | первым версиям |',
      '| Своя реализация | полный контроль | дороже в поддержке | командам с ресурсом |',
      '| Гибрид | быстрый старт, рост по частям | нужно следить за стыками | большинству продуктов |',
      '',
      'Практическое правило: **начинайте с готового и переписывайте узкое место**, когда оно',
      'действительно начнёт мешать. Переписывание «на всякий случай» почти всегда дороже,',
      'чем кажется.',
      '',
      '- если узкое место в скорости — оптимизируйте запросы, а не архитектуру;',
      '- если в деньгах — считайте стоимость на одного пользователя;',
      '- если в людях — автоматизируйте релизы и проверки.',
    ],
    en: [
      'I put the comparison into a table — the forks are easier to see this way.',
      '',
      '| Approach | Pros | Cons | Who it fits |',
      '| --- | --- | --- | --- |',
      '| Ready made product | fast start | paid, little flexibility | first versions |',
      '| In house build | full control | expensive to maintain | teams with capacity |',
      '| Hybrid | fast start, grow in parts | watch the seams | most products |',
      '',
      'Rule of thumb: **start with the ready made option and rewrite the bottleneck** once it',
      'really starts to hurt. Rewriting just in case is almost always more expensive than it looks.',
      '',
      '- if the bottleneck is speed — optimise queries, not the architecture;',
      '- if it is money — measure the cost per user;',
      '- if it is people — automate releases and checks.',
    ],
  },
  {
    id: 'tests',
    triggers: ['тест', 'покрыт', 'test', 'coverage', 'vitest', 'jest'],
    ru: [
      '## Тесты для этого места',
      '',
      'Минимальный набор, который окупается сразу:',
      '',
      '- **пустой ввод** — не должно быть исключения;',
      '- **отмена запроса** — поток закрывается, частичный ответ сохраняется;',
      '- **ошибка сети** — пользователь видит сообщение и кнопку «Повторить».',
      '',
      '```ts',
      "it('сохраняет частичный ответ после остановки', async () => {",
      '  const { store, abort } = await startStream();',
      '  abort();',
      "  expect(store.lastMessage()).toMatchObject({ status: 'complete' });",
      '});',
      '```',
      '',
      'Запуск всего прогона: `npm test`.',
    ],
    en: [
      '## Tests for this place',
      '',
      'The minimal set that pays off right away:',
      '',
      '- **empty input** — there must be no exception;',
      '- **cancelled request** — the stream closes and the partial answer is saved;',
      '- **network error** — the user sees a message and a Retry button.',
      '',
      '```ts',
      "it('keeps the partial answer after a stop', async () => {",
      '  const { store, abort } = await startStream();',
      '  abort();',
      "  expect(store.lastMessage()).toMatchObject({ status: 'complete' });",
      '});',
      '```',
      '',
      'Run the whole suite with `npm test`.',
    ],
  },
];

/** Общие ответы: используются, когда в запросе нет знакомых ключевых слов. */
const GENERIC_TEMPLATES: readonly AnswerTemplate[] = [
  {
    id: 'generic-steps',
    triggers: [],
    ru: [
      'Хороший вопрос. Соберу ответ по шагам — так его проще проверить.',
      '',
      '1. **Что уже известно.** Опишите текущую ситуацию: что работает, а что мешает.',
      '2. **Что нужно получить.** Сформулируйте результат одним предложением — критерии',
      '   готовности появятся сами.',
      '3. **Как проверить.** Придумайте самый дешёвый способ убедиться, что решение работает.',
      '',
      'Если расскажете подробнее, разберу ваш случай конкретнее.',
    ],
    en: [
      'Good question. I will answer step by step — that makes it easier to verify.',
      '',
      '1. **What is already known.** Describe the situation: what works and what blocks you.',
      '2. **What you need.** State the result in one sentence — the definition of done follows.',
      '3. **How to verify.** Find the cheapest way to check that the solution works.',
      '',
      'Tell me more and I will look at your case in detail.',
    ],
  },
  {
    id: 'generic-parts',
    triggers: [],
    ru: [
      'Разложил бы задачу на три части:',
      '',
      '| Часть | Вопрос, на который отвечает |',
      '| --- | --- |',
      '| Данные | что у нас есть и в каком виде |',
      '| Логика | что с этими данными происходит |',
      '| Интерфейс | как человек это видит и меняет |',
      '',
      'Начинать стоит с данных: почти всегда сложности приходят оттуда, а не из интерфейса.',
      '',
      'Подходит такая рамка или нужен разбор конкретного случая?',
    ],
    en: [
      'I would split the task into three parts:',
      '',
      '| Part | The question it answers |',
      '| --- | --- |',
      '| Data | what we have and in which shape |',
      '| Logic | what happens to that data |',
      '| Interface | how a person sees and changes it |',
      '',
      'Start with the data: trouble almost always comes from there, not from the interface.',
      '',
      'Does this frame work for you, or do you need a specific case reviewed?',
    ],
  },
];

/** Выбирает ответ: сначала по ключевым словам, иначе — случайный общий. */
export function pickAnswer(prompt: string, language: Language, random: () => number): string {
  const text = prompt.toLowerCase();
  const matched = KEYWORD_TEMPLATES.find((template) =>
    template.triggers.some((trigger) => text.includes(trigger)),
  );

  const pool = matched ? [matched] : GENERIC_TEMPLATES;
  const index = Math.min(pool.length - 1, Math.floor(random() * pool.length));
  return pool[index][language].join('\n');
}

/** Текст ошибки заглушки: интерфейс показывает его в сообщении ассистента. */
export const ERROR_MESSAGES: Record<Language, string> = {
  ru: 'Демонстрационная модель не ответила. Попробуйте отправить сообщение ещё раз.',
  en: 'The demo model did not answer. Please send the message again.',
};
