import type { Language, MessageAttachment } from '../types.js';

/**
 * Заготовки ответов заглушки.
 *
 * Шаблон выбирается по ключевым словам в запросе, а если ничего не совпало —
 * случайный из общих. Тексты размечены markdown: интерфейс проверяет на них
 * списки, таблицы и блоки кода.
 */
interface AnswerTemplate {
  id: string;
  triggers: readonly string[];
  ru: readonly string[];
  en: readonly string[];
}

const KEYWORD_TEMPLATES: readonly AnswerTemplate[] = [
  {
    id: 'greeting',
    triggers: ['привет', 'здравствуй', 'добрый день', 'добрый вечер', 'hello', 'hi ', 'hey'],
    ru: [
      'Привет! Я — **Ketner AI**, интеллектуальный ассистент для написания и анализа кода,',
      'проектирования архитектуры и решения инженерных задач.',
      '',
      'Что уже работает в интерфейсе:',
      '',
      '- **стриминг ответа** — текст приходит порциями в реальном времени;',
      '- **markdown** — списки, таблицы, `код` в строке и блоки кода с кнопкой «Копировать»;',
      '- **история** — диалоги сохраняются и переживают перезагрузку страницы;',
      '- **управление** — остановка генерации, повторная отправка и редактирование сообщения.',
      '',
      'Спросите меня о чём угодно: напишите функцию, сделайте рефакторинг или разберите архитектурный вопрос.',
    ],
    en: [
      'Hello! I am **Ketner AI** — an intelligent assistant designed for software engineering,',
      'code synthesis, architecture design, and problem solving.',
      '',
      'What already works in the interface:',
      '',
      '- **streaming output** — responses arrive progressively in real time;',
      '- **markdown** — lists, tables, inline `code`, and syntax-highlighted code blocks with Copy buttons;',
      '- **conversation history** — chats survive browser reloads and sync across devices;',
      '- **controls** — stop generation, regenerate, and edit previous messages.',
      '',
      'Ask me anything: refactor a function, architect a system, or analyze code.',
    ],
  },
  {
    id: 'qwen',
    triggers: [
      'qwen',
      'квен',
      'модель',
      'кто ты',
      'что за модель',
      'какая модель',
      'какая ты модель',
      'какую модель используешь',
      'who are you',
      'what model',
      'which model',
    ],
    ru: [
      'Я работаю на базе модели **{model}** в Ketner AI — интеллектуальном ассистенте для анализа кода, архитектуры и решения инженерных задач.',
      '',
      '### Специализация:',
      '- ⚡ **Продвинутое программирование**: TypeScript, JavaScript, Python, Go, Rust, C++, SQL.',
      '- 🛠️ **Инженерия и архитектура**: проектирование масштабируемых систем, рефакторинг, отладка багов.',
      '- 📊 **Работа со сложными данными**: генерация JSON, Markdown-таблиц, регулярных выражений.',
      '- 🌐 **Полная мультиязычность**: свободные ответы на русском и английском языках.',
      '',
      'Задайте мне любую задачу по коду или алгоритмам!',
    ],
    en: [
      'I am powered by the **{model}** model in Ketner AI — an intelligent assistant designed for software engineering and problem solving.',
      '',
      '### Core competencies:',
      '- ⚡ **Advanced programming**: TypeScript, JavaScript, Python, Go, Rust, C++, SQL, and more.',
      '- 🛠️ **Engineering & Architecture**: clean code architecture, refactoring, vulnerability audit.',
      '- 📊 **Data handling**: schema synthesis, JSON formatting, Markdown tables, regex creation.',
      '- 🌐 **Full multilingual fluency**: natural communication in both Russian and English.',
      '',
      'Feel free to give me any coding or algorithmic challenge!',
    ],
  },
  {
    id: 'git-action-request',
    triggers: [
      'ты можешь привязать',
      'а ты можешь привязать',
      'можешь привязать',
      'привяжи репозиторий',
      'привяжи https',
      'привяжи git',
      'can you link repo',
    ],
    ru: [
      'В Ketner AI теперь доступна **полная привязка локальных папок и Git-репозиториев**!',
      '',
      'Нажмите на иконку скрепки 📎 или кнопку «Привязать папку / репо» над строкой ввода:',
      '',
      '1. **📁 Привязать локальную папку** — выберите любую директорию на вашем компьютере. Браузер прочитает файлы кода, а я проиндексирую структуру проекта.',
      '2. **🐙 Привязать GitHub-репозиторий** — укажите ссылку на репозиторий GitHub (например, `https://github.com/facebook/react` или `owner/repo`).',
      '',
      'После привязки я буду видеть все файлы проекта, отвечать на вопросы по коду, искать нужные функции, компоненты и предлагать точные правки!',
    ],
    en: [
      'Ketner AI now features **full local folder and Git repository linking**!',
      '',
      'Click the paperclip 📎 icon or the "Link folder / repo" button above the input field:',
      '',
      '1. **📁 Link local folder** — select any directory on your computer to index codebase files.',
      '2. **🐙 Link GitHub repository** — enter a GitHub repository link or owner/repo format.',
      '',
      'Once linked, I will have full project awareness: analyzing files, searching components, refactoring code, and answering architecture questions!',
    ],
  },
  {
    id: 'git-repo',
    triggers: [
      'как привязать репозитори',
      'привязать репозитори',
      'как привязать проект к git',
      'подключить репозитори',
      'как связать с github',
      'как привязать гит',
      'инструкция git',
      'how to link repository',
      'connect git repo',
    ],
    ru: [
      '### Как привязать существующий проект к Git-репозиторию (GitHub / GitLab)',
      '',
      'Пошаговая инструкция для терминала:',
      '',
      '**1. Перейдите в папку проекта и инициализируйте Git:**',
      '```bash',
      'cd /путь/к/вашему/проекту',
      'git init',
      '```',
      '',
      '**2. Добавьте файлы и создайте первый коммит:**',
      '```bash',
      'git add .',
      'git commit -m "Initial commit: запуск проекта"',
      '```',
      '',
      '**3. Установите основную ветку `main`:**',
      '```bash',
      'git branch -M main',
      '```',
      '',
      '**4. Подключите удалённый репозиторий (remote origin):**',
      '```bash',
      '# Если используете HTTPS:',
      'git remote add origin https://github.com/username/repository.git',
      '',
      '# Или если используете SSH-ключи:',
      'git remote add origin git@github.com:username/repository.git',
      '```',
      '',
      '**5. Отправьте код на сервер:**',
      '```bash',
      'git push -u origin main',
      '```',
      '',
      '💡 *Совет:* не забудьте создать файл `.gitignore`, чтобы исключить `node_modules/`, секретные файлы `.env` и артефакты сборки `dist/`.',
    ],
    en: [
      '### How to link an existing project to a Git repository (GitHub / GitLab)',
      '',
      '**1. Initialize Git in your project folder:**',
      '```bash',
      'cd /path/to/project',
      'git init',
      '```',
      '',
      '**2. Stage and commit your files:**',
      '```bash',
      'git add .',
      'git commit -m "Initial commit"',
      '```',
      '',
      '**3. Set primary branch to `main`:**',
      '```bash',
      'git branch -M main',
      '```',
      '',
      '**4. Add remote origin:**',
      '```bash',
      'git remote add origin https://github.com/username/repository.git',
      '```',
      '',
      '**5. Push code:**',
      '```bash',
      'git push -u origin main',
      '```',
    ],
  },
  {
    id: 'code',
    triggers: ['код', 'рефактор', 'функци', 'баг', 'code', 'refactor', 'function', 'bug'],
    ru: [
      '## Что можно улучшить',
      '',
      'Разложу замечания по приоритетам — от дешёвых правок к архитектурным.',
      '',
      '**1. Убрать повторяющиеся проверки**',
      '',
      '```ts',
      'type Nullable<T> = T | null | undefined;',
      '',
      'function present<T>(value: Nullable<T>): value is T {',
      '  return value !== null && value !== undefined;',
      '}',
      '',
      'const activeUsers = users.filter(present).filter((user) => user.active);',
      '```',
      '',
      '**2. Разделить чистые функции и побочные эффекты**',
      '',
      '- чистые функции — в `lib/`, их легко покрыть тестами;',
      '- работу с сетью и хранилищем — в `api/` и `store/`.',
      '',
      '**3. Проверить границы**',
      '',
      '| Случай | Что проверяем |',
      '| --- | --- |',
      '| Пустой ввод | функция не бросает исключение |',
      '| Очень длинный текст | обрезка не рвёт эмодзи |',
      '| Недоступный API | пользователь видит понятную ошибку |',
      '',
      'Пришлите сам код — разберу конкретные места построчно.',
    ],
    en: [
      '## What can be improved',
      '',
      'Here are the notes ordered by priority — from cheap fixes to architectural ones.',
      '',
      '**1. Remove repeated checks**',
      '',
      '```ts',
      'type Nullable<T> = T | null | undefined;',
      '',
      'function present<T>(value: Nullable<T>): value is T {',
      '  return value !== null && value !== undefined;',
      '}',
      '',
      'const activeUsers = users.filter(present).filter((user) => user.active);',
      '```',
      '',
      '**2. Separate pure functions from side effects**',
      '',
      '- pure functions belong in `lib/`, they are easy to test;',
      '- network and storage work belongs in `api/` and `store/`.',
      '',
      '**3. Cover the edges**',
      '',
      '| Case | What we check |',
      '| --- | --- |',
      '| Empty input | the function does not throw |',
      '| Very long text | truncation does not break emoji |',
      '| API unavailable | the user sees a clear error |',
      '',
      'Send the code itself and I will review the exact lines.',
    ],
  },
  {
    id: 'data',
    triggers: ['sql', 'nosql', 'бд', 'база данных', 'индекс', 'database', 'postgres', 'транзакц'],
    ru: [
      '### Коротко',
      '',
      'SQL — про жёсткую схему и связи, NoSQL — про свободную структуру и горизонтальное',
      'масштабирование. Выбирают не «что современнее», а что требует задача.',
      '',
      '| Критерий | SQL | NoSQL |',
      '| --- | --- | --- |',
      '| Схема | задаётся заранее, есть миграции | гибкая, поля могут отличаться |',
      '| Связи | `JOIN`, внешние ключи | вложенные документы или ручная сборка |',
      '| Масштабирование | вертикальное, реже шардирование | горизонтальное «из коробки» |',
      '| Гарантии | ACID по умолчанию | часто eventual consistency |',
      '',
      '**Когда SQL:** транзакции, отчётность, сложные связи, деньги и заказы.',
      '',
      '**Когда NoSQL:** быстро меняющаяся структура, огромный поток записей, кэш и сессии.',
      '',
      '> В прототипе Ketner AI диалоги и сообщения описаны как обычные таблицы: связи простые,',
      '> а согласованность данных важнее скорости записи.',
    ],
    en: [
      '### In short',
      '',
      'SQL is about a strict schema and relations, NoSQL is about a flexible structure and',
      'horizontal scaling. The choice follows the task, not the trend.',
      '',
      '| Criterion | SQL | NoSQL |',
      '| --- | --- | --- |',
      '| Schema | defined upfront, migrations | flexible, fields may differ |',
      '| Relations | `JOIN`, foreign keys | embedded documents or manual assembly |',
      '| Scaling | vertical, sharding later | horizontal out of the box |',
      '| Guarantees | ACID by default | often eventual consistency |',
      '',
      '**Choose SQL for:** transactions, reporting, complex relations, money and orders.',
      '',
      '**Choose NoSQL for:** fast changing structure, huge write volume, caches and sessions.',
      '',
      '> In the Ketner AI prototype conversations and messages are plain tables: relations are',
      '> simple, and consistency matters more than write speed.',
    ],
  },
  {
    id: 'plan',
    triggers: ['план', 'запуск', 'roadmap', 'недел', 'этап', 'plan', 'launch', 'week'],
    ru: [
      '## План запуска на 4 недели',
      '',
      '**Неделя 1 — фундамент**',
      '',
      '1. Зафиксировать метрику успеха и целевую аудиторию.',
      '2. Собрать лендинг и форму списка ожидания.',
      '',
      '**Неделя 2 — продукт**',
      '',
      '1. Довести основной сценарий до конца, без обходных путей.',
      '2. Закрыть дыры в онбординге и пустых состояниях.',
      '',
      '**Неделя 3 — приватная бета**',
      '',
      '1. Пригласить 20–30 человек из целевой аудитории.',
      '2. Собрать обратную связь по трём вопросам: что понятно, что мешает, за чем вернутся.',
      '',
      '**Неделя 4 — публичный запуск**',
      '',
      '1. Подготовить каналы: рассылка, профильные сообщества, личные приглашения.',
      '2. Держать наготове быстрые правки по итогам первой недели.',
      '',
      '| Риск | Как снижаем |',
      '| --- | --- |',
      '| Не хватает времени | оставляем один сценарий вместо трёх |',
      '| Мало отклика в бете | пишем участникам лично |',
    ],
    en: [
      '## Four week launch plan',
      '',
      '**Week 1 — foundation**',
      '',
      '1. Fix the success metric and the target audience.',
      '2. Ship the landing page and the waitlist form.',
      '',
      '**Week 2 — product**',
      '',
      '1. Bring the main flow to the end, without workarounds.',
      '2. Close the gaps in onboarding and empty states.',
      '',
      '**Week 3 — private beta**',
      '',
      '1. Invite 20–30 people from the target audience.',
      '2. Collect feedback on three questions: what is clear, what blocks them, what brings',
      '   them back.',
      '',
      '**Week 4 — public launch**',
      '',
      '1. Prepare the channels: newsletter, communities, personal invites.',
      '2. Keep quick fixes ready based on the first week.',
      '',
      '| Risk | How we reduce it |',
      '| --- | --- |',
      '| Not enough time | keep one flow instead of three |',
      '| Low beta response | message participants personally |',
    ],
  },
  {
    id: 'compare',
    triggers: ['сравн', 'разниц', 'таблиц', 'compare', 'difference', 'table', 'плюсы'],
    ru: [
      'Собрал сравнение в таблицу — так развилки видны сразу.',
      '',
      '| Подход | Плюсы | Минусы | Кому подходит |',
      '| --- | --- | --- | --- |',
      '| Готовое решение | быстрый старт | платно и мало гибкости | первым версиям |',
      '| Своя реализация | полный контроль | дороже в поддержке | командам с ресурсом |',
      '| Гибрид | быстрый старт, рост по частям | нужно следить за стыками | большинству продуктов |',
      '',
      'Практическое правило: **начинайте с готового и переписывайте узкое место**, когда оно',
      'действительно начнёт мешать. Переписывание «на всякий случай» почти всегда дороже,',
      'чем кажется.',
      '',
      '- если узкое место в скорости — оптимизируйте запросы, а не архитектуру;',
      '- если в деньгах — считайте стоимость на одного пользователя;',
      '- если в людях — автоматизируйте релизы и проверки.',
    ],
    en: [
      'I put the comparison into a table — the forks are easier to see this way.',
      '',
      '| Approach | Pros | Cons | Who it fits |',
      '| --- | --- | --- | --- |',
      '| Ready made product | fast start | paid, little flexibility | first versions |',
      '| In house build | full control | expensive to maintain | teams with capacity |',
      '| Hybrid | fast start, grow in parts | watch the seams | most products |',
      '',
      'Rule of thumb: **start with the ready made option and rewrite the bottleneck** once it',
      'really starts to hurt. Rewriting just in case is almost always more expensive than it looks.',
      '',
      '- if the bottleneck is speed — optimise queries, not the architecture;',
      '- if it is money — measure the cost per user;',
      '- if it is people — automate releases and checks.',
    ],
  },
  {
    id: 'tests',
    triggers: ['тест', 'покрыт', 'test', 'coverage', 'vitest', 'jest'],
    ru: [
      '## Тесты для этого места',
      '',
      'Минимальный набор, который окупается сразу:',
      '',
      '- **пустой ввод** — не должно быть исключения;',
      '- **отмена запроса** — поток закрывается, частичный ответ сохраняется;',
      '- **ошибка сети** — пользователь видит сообщение и кнопку «Повторить».',
      '',
      '```ts',
      "it('сохраняет частичный ответ после остановки', async () => {",
      '  const { store, abort } = await startStream();',
      '  abort();',
      "  expect(store.lastMessage()).toMatchObject({ status: 'complete' });",
      '});',
      '```',
      '',
      'Запуск всего прогона: `npm test`.',
    ],
    en: [
      '## Tests for this place',
      '',
      'The minimal set that pays off right away:',
      '',
      '- **empty input** — there must be no exception;',
      '- **cancelled request** — the stream closes and the partial answer is saved;',
      '- **network error** — the user sees a message and a Retry button.',
      '',
      '```ts',
      "it('keeps the partial answer after a stop', async () => {",
      '  const { store, abort } = await startStream();',
      '  abort();',
      "  expect(store.lastMessage()).toMatchObject({ status: 'complete' });",
      '});',
      '```',
      '',
      'Run the whole suite with `npm test`.',
    ],
  },
];

/** Общие ответы: используются, когда в запросе нет знакомых ключевых слов. */
const GENERIC_TEMPLATES: readonly AnswerTemplate[] = [
  {
    id: 'generic-steps',
    triggers: [],
    ru: [
      'Хороший вопрос. Соберу ответ по шагам — так его проще проверить.',
      '',
      '1. **Что уже известно.** Опишите текущую ситуацию: что работает, а что мешает.',
      '2. **Что нужно получить.** Сформулируйте результат одним предложением — критерии',
      '   готовности появятся сами.',
      '3. **Как проверить.** Придумайте самый дешёвый способ убедиться, что решение работает.',
      '',
      'Если расскажете подробнее, разберу ваш случай конкретнее.',
    ],
    en: [
      'Good question. I will answer step by step — that makes it easier to verify.',
      '',
      '1. **What is already known.** Describe the situation: what works and what blocks you.',
      '2. **What you need.** State the result in one sentence — the definition of done follows.',
      '3. **How to verify.** Find the cheapest way to check that the solution works.',
      '',
      'Tell me more and I will look at your case in detail.',
    ],
  },
  {
    id: 'generic-parts',
    triggers: [],
    ru: [
      'Разложил бы задачу на три части:',
      '',
      '| Часть | Вопрос, на который отвечает |',
      '| --- | --- |',
      '| Данные | что у нас есть и в каком виде |',
      '| Логика | что с этими данными происходит |',
      '| Интерфейс | как человек это видит и меняет |',
      '',
      'Начинать стоит с данных: почти всегда сложности приходят оттуда, а не из интерфейса.',
      '',
      'Подходит такая рамка или нужен разбор конкретного случая?',
    ],
    en: [
      'I would split the task into three parts:',
      '',
      '| Part | The question it answers |',
      '| --- | --- |',
      '| Data | what we have and in which shape |',
      '| Logic | what happens to that data |',
      '| Interface | how a person sees and changes it |',
      '',
      'Start with the data: trouble almost always comes from there, not from the interface.',
      '',
      'Does this frame work for you, or do you need a specific case reviewed?',
    ],
  },
];

/** Выбирает ответ: с учётом привязанного проекта/файлов, по ключевым словам или общий. */
export function pickAnswer(
  prompt: string,
  language: Language,
  random: () => number,
  selectedModelName?: string,
  attachments?: MessageAttachment[],
  workspaceContext?: {
    name: string;
    type?: string;
    pathOrUrl?: string;
    filesCount?: number;
    files?: Array<{ path: string; size?: number; content?: string }>;
  },
): string {
  // 1. Если привязана рабочая папка или репозиторий
  if (workspaceContext) {
    const isEn = language === 'en';
    const projName = workspaceContext.name;
    const count = workspaceContext.filesCount || (workspaceContext.files ? workspaceContext.files.length : 0);
    const sampleFiles = workspaceContext.files?.slice(0, 8).map((f) => `- \`${f.path}\``).join('\n') || '';

    if (isEn) {
      return [
        `I am actively connected to your workspace **${projName}** (${count} indexed files).`,
        '',
        '### Project Context Loaded:',
        sampleFiles ? `${sampleFiles}\n` : '',
        'I am analyzing your codebase and ready to assist you:',
        '- **Code architecture & walkthrough**: explain dependencies and file structure',
        '- **Implementation & refactoring**: write idiomatic functions and fix errors',
        '- **Search**: locate classes, handlers, hooks, and endpoints across files',
        '',
        prompt ? `Regarding your request: "${prompt}" — let's review the code logic.` : 'What task or file shall we work on next?',
      ].filter(Boolean).join('\n');
    }

    return [
      `Я подключен к вашей кодовой базе **${projName}** (${count} проиндексированных файлов).`,
      '',
      '### Загруженный контекст проекта:',
      sampleFiles ? `${sampleFiles}\n` : '',
      'Я проанализировал структуру репозитория и готов работать с кодом:',
      '- **Анализ архитектуры и файлов**: расскажу, как устроены модули и где находится логика;',
      '- **Разработка и рефакторинг**: напишу функции, компоненты или исправлю баги;',
      '- **Поиск по кодовой базе**: найду нужные функции, хуки или маршруты API.',
      '',
      prompt ? `По вашему запросу: *«${prompt}»* — готов внести изменения или разобрать код. Что делаем дальше?` : 'С каким файлом или задачей начнём работу?',
    ].filter(Boolean).join('\n');
  }

  // 2. Если прикреплены файлы / фото / видео
  if (attachments && attachments.length > 0) {
    const isEn = language === 'en';
    const filesOverview = attachments.map((a) => `- **${a.name}** (${a.category.toUpperCase()})`).join('\n');

    if (isEn) {
      return [
        `I received and processed your attachments (${attachments.length}):`,
        '',
        filesOverview,
        '',
        attachments.some((a) => a.category === 'code' || a.category === 'document')
          ? 'I reviewed the file contents and code structure. The syntax and formatting look valid.'
          : 'Media files (images/videos) loaded successfully into the conversation.',
        '',
        prompt ? `Regarding your prompt: "${prompt}": I am ready to analyze or process these files.` : 'How would you like me to process these attachments?',
      ].join('\n');
    }

    return [
      `Я получил и обработал ваши вложения (${attachments.length}):`,
      '',
      filesOverview,
      '',
      attachments.some((a) => a.category === 'code' || a.category === 'document')
        ? 'Содержимое текстовых файлов и кода успешно прочитано и добавлено в контекст для анализа.'
        : 'Медиафайлы (фото / видео) успешно прикреплены к диалогу.',
      '',
      prompt ? `По вашему запросу: *«${prompt}»* — готов выполнить анализ или доработку.` : 'Что требуется сделать с прикреплёнными файлами?',
    ].join('\n');
  }

  const text = prompt.toLowerCase();
  const matched = KEYWORD_TEMPLATES.find((template) =>
    template.triggers.some((trigger) => text.includes(trigger)),
  );

  const pool = matched ? [matched] : GENERIC_TEMPLATES;
  const index = Math.min(pool.length - 1, Math.floor(random() * pool.length));
  let answer = pool[index][language].join('\n');

  const modelDisplay = selectedModelName || 'DeepSeek V4.1 Flash';
  answer = answer.replace(/\{model\}/g, modelDisplay);
  return answer;
}

/** Текст ошибки: интерфейс показывает его в сообщении ассистента. */
export const ERROR_MESSAGES: Record<Language, string> = {
  ru: 'Модель не ответила на запрос. Попробуйте отправить сообщение ещё раз.',
  en: 'The AI model did not answer. Please try sending the message again.',
};
